### ISSUE TITLE
Login doesn't work after navigating from exchange view.

### ISSUE THREAD

**Issue by bartekn** [irisli/stellarterm#103]
1. Open https://stellarterm.com/
2. Go to Exchange (it will open XLM-CNY market).
3. Go to Account.
4. Enter secret, click "Log in".
5. Nothing happens.

Chrome 61.0.3163.100

**Comment by irisli** [comment]
Ah! This bug has been bugging me for a long time and I could'nt repro it. Thanks!

**Comment by irisli** [comment]
Okay, so the logging in is fine but my event subscription system is broken for some reason. Good time to refactor the event listening. thanks!

**Comment by irisli** [comment]
Thanks

https://github.com/irisli/stellarterm/commit/6ec8e0c574b8bb2142f0425810a3749645ba0d27
