### ISSUE TITLE
Diagrams and Markets info

### ISSUE THREAD

**Issue by Smartlands** [irisli/stellarterm#109]
Historic price diagrams are not displayed and the information about price and trading volume is not being updated for few days.

**Comment by irisli** [comment]
Horizon was updated and I have to update StellarTerm to work with the current Horizon

**Comment by Smartlands** [comment]
Ok, thanks! When do you expect it to be updated?

**Comment by irisli** [comment]
Some time around next week. The history charts don't work but the trading and the orderbook table should still work.

For history charts, LuPoEx (https://lupoex.com/) is working.

**Comment by irisli** [comment]
Done
