### ISSUE TITLE
Asset Stranded

### ISSUE THREAD

**Issue by kikera** [irisli/stellarterm#112]
Hi guys,
I've transfered a few BTC to the BTC stronghold.co asset on my StellarTerm account, to trade for XLMs. But it seems there are 0 offers to sell on that market.

I dont know how to move those BTC to market where there is more volume to trade for the XLMs. Is that possible? or are they stranded.

Best regards,

**Comment by irisli** [comment]
Try this market pair: https://stellarterm.com/#exchange/XLM-stronghold.co/BTC-stronghold.co

Though I think for now, you are better off using a traditional exchange.

**Comment by kikera** [comment]
Hi Irisli,

That worked perfectly, thank you for the help!
