### ISSUE TITLE
Can't buy XLM on BTC-apay.io market

### ISSUE THREAD

**Issue by malinovskymax** [irisli/stellarterm#118]
![bug_cannot_buy_xlm](https://user-images.githubusercontent.com/13059510/34605662-18792a1c-f215-11e7-8d72-bb8db9577827.png)

See screenshot and feel free to ask me additional questions.

**Comment by irisli** [comment]
Your account got stuck because of the minimum balance problem and you need to send more lumens to it.

**Comment by malinovskymax** [comment]
Hmm, really? Account has 30 lumens. 20 is a minimum balance and 10 is for trust line for BTC-apay.io assets, as I understand. How much lumens I need to make such order and why? And I think it would be better to add more clear error handling rather than just throwing an unclear exception to browser's console. I think I can add error handling, but first please explain me why I were able to create `sell` order for the same asset with residual balance of 30 lumens, but I am unable to create `buy` order with the same residual balance?

**Comment by irisli** [comment]
If you have exactly 30.0000000 lumens, the Stellar network won't let you create a transaction because it doesn't let you go below 30.0000000. This is a pain point with Stellar.

I just sent you 0.1 lumens. Try again and see if it works.

**Comment by malinovskymax** [comment]
Thank you, but I still got an error.
At least, now the source of the error is clear. I'll return you your lumens, and, probably, sometime later I will rescue my lumens from that trap.
![still_error](https://user-images.githubusercontent.com/13059510/34776594-1622acfc-f620-11e7-830e-ce2413309212.png)

**Comment by irisli** [comment]
Ohhhh okay thanks for finding this.

I just realized this was a bug i fixed 2 days ago.

Thank you for helping me realize that I fixed a important bug :)

**Comment by irisli** [comment]
I just sent you some more lumens that should get you unstuck :)

You can send them back whenever

**Comment by malinovskymax** [comment]
Oh, thank you, I'll try :)

**Comment by irisli** [comment]
The minimum balance also just got reduced to 1 XLM
