### ISSUE TITLE
Would be cool to have a ticker for the pairs but maybe volume info is hard to get out of horizon

### ISSUE THREAD

**Issue by jedmccaleb** [irisli/stellarterm#12]

**Comment by irisli** [comment]
I think I will have to implement my history aggregator. Then I can easily show the trend of whether the price went up or down.

**Comment by jedmccaleb** [comment]
Some other people were wanting to do this. Maybe it could be a common service

**Comment by irisli** [comment]
If I do end up making my own history aggregator, it'll be open for public access. I anticipate it'll be very inexpensive since I will use S3 for hosting with forever-cache and cloudflare for the free bandwidth.

**Comment by irisli** [comment]
Woot done
