### ISSUE TITLE
StellarSdk.Config.setAllowHttp(true)

### ISSUE THREAD

**Issue by nengine** [irisli/stellarterm#123]
Hello, I do not have https setup on private test horizon server, so please let me know where I can set StellarSdk.Config.setAllowHttp(true) (or) if this is something can be done from the config file?

Thanks.

**Comment by irisli** [comment]
You can fork StellarTerm and make the changes to your own private StellarTerm.

Add it here: https://github.com/irisli/stellarterm/blob/master/src/app.jsx

I wont add it to StellarTerm out of security concerns

**Comment by nengine** [comment]
Ok thanks a lot.

**Comment by irisli** [comment]
Here are instructions on how to build the project: https://github.com/irisli/stellarterm#environment-setup

**Comment by irisli** [comment]
Custom network instructions: https://github.com/irisli/stellarterm#stellarterm-client-custom-network

**Comment by nengine** [comment]
Very nice!  I have removed default anchors from the directory.json and added some test anchors.  On the markets page everything is still showing, but the one I added not showing.  Not so sure what I am doing wrong..

**Comment by irisli** [comment]
Markets page is based on the ticker.json api.

Local changes won't reflect in the markets page.

**Comment by nengine** [comment]
Ok i see. Thanks again!
