### ISSUE TITLE
Unable to send trusted asset

### ISSUE THREAD

**Issue by tempofr** [irisli/stellarterm#127]
Sending to 
in*tempo.eu.com GBTPRPPKDWFZTWMOPNG6OLVU3HYUEIP7OOWQZRRJ72E72GY6UDMOZEUR

which trusts EURT 
GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S

from 
GA4GYS22FOQKWPQT7SSSBAHSJ3HWAGXZDBC3OWIBQOTQ42EUVDJW6VP6
which also has 1.1242082 EURT

When put the destination field in*tempo.eu.com I am unable to select the asset (it only shows XLM). However when I paste the full public key in it works fine.

Maybe there is an issue with the lookup.

Thanks

**Comment by irisli** [comment]
Hm, can you try again?

I added a new thing to the send pane that shows assets that you have but receiver doesn't trust.

**Comment by irisli** [comment]
I "logged in" as your user (I added a developer tool to view as an account with just pubkey):
```js
window.driver.handlers.logIn('',{publicKey:'GA4GYS22FOQKWPQT7SSSBAHSJ3HWAGXZDBC3OWIBQOTQ42EUVDJW6VP6'})
```

![image](https://user-images.githubusercontent.com/5728307/35257019-cc96e720-ffab-11e7-9dc0-53363208cf67.png)

**Comment by irisli** [comment]
I think it should be fixed
