### ISSUE TITLE
Addresses below currency icons causing confusion

### ISSUE THREAD

**Issue by bbjunkie** [irisli/stellarterm#130]
1st time on GitHub so forgive me if this is in the wrong place. 

The addresses shown in the currency logo cause confusion for new users.

I know of 2 users who have lost tokens by giving this address out as the wallet address for that coin.

Suggest this be obfuscated or some sort of disclaimer pop up when anyone tries to copy this address to clipboard.

Keep up the good work guys

**Comment by irisli** [comment]
Thanks! Fixing it
