### ISSUE TITLE
StellarTerm inflation pool prompt is unclear

### ISSUE THREAD

**Issue by janclarin** [irisli/stellarterm#135]
Is the inflation pool distributed back to users of StellarTerm? It's a very unclear based on the message "your account will vote to support the future of StellarTerm (no further action needed)" and the fact that other inflation pools like [Lumenaut](https://lumenaut.net/) redistribute the inflation lumens to their voters.

Based on the message, I assume that they are *not* distributed out to the user. That's okay and totally understandable, as maintaining this project is a lot of work, but changing inflation pools needs to be more explicit - it doesn't stand out on the welcome page and is easily missed.

Another idea might be to only prompt users to change their inflation pools if they don't already have a pool. If they have an inflation pool set, they should only be prompted the first time (storing a cookie to prevent future prompting) with a clearer message stating that they will be switching inflation pools and that the proceeds will be kept by StellarTerm.

Regardless, thank you for maintaining this project - it's spectacular. I'm glad the for-sale sign is gone and that you're going to continue maintaining it. Definitely consider having a donation address on the site, I'd love to donate a some lumens!

**Comment by irisli** [comment]
Okay, I'll make it more clear. I explicitly don't want donations since I think they hurt more than they help.

**Comment by irisli** [comment]
Done: https://github.com/irisli/stellarterm/commit/7dcff293da7b36b0b8b2fae5a978323951336f8a

**Comment by irisli** [comment]
I also now no longer ask users that are already point to lumenaut

**Comment by janclarin** [comment]
Wow, thank you for such a fast response. Highly appreciated! On another note, I'm really interested in contributing to the project, so look out for some PRs from me 👍

**Comment by irisli** [comment]
Okay, if you need any pointers, just let me know, I'll be happy to help!
