### ISSUE TITLE
error on trade to buy MOBI

### ISSUE THREAD

**Issue by kyungsoomim** [irisli/stellarterm#137]
Good morning!

I tried to buy MOBI on stellar term around 50 times. But the system showed attached message and couldn't made transactions.
Every time I tried, the trade fee deducted systemically even the transaction failed.

I Kindly request your recommendation and/or solution for above mentioned problem.

Thanks in advance.

![stellarterm trade error](https://user-images.githubusercontent.com/32034368/35276703-994ceb3a-0087-11e8-914a-fa17c13d081a.jpg)

**Comment by irisli** [comment]
Can you give me your public key (begins with a G) so that I can debug it?

Thanks

**Comment by kyungsoomim** [comment]
Dear Ms/Mr  iris Li

Thank you for  the kind reply

  I find  the solution for the trade error on stellarterm that i mentioned.

I changed the limit at "Mystellar tool" manage trustline tab.


Regards


2018. 1. 24. 오전 7:40에 "Iris Li" <notifications@github.com>님이 작성:
