### ISSUE TITLE
Refactor Driver

### ISSUE THREAD

**Issue by irisli** [irisli/stellarterm#138]
This piece of crap: https://github.com/irisli/stellarterm/blob/master/src/lib/Driver.js#L74

Should be refactored into this piece of lesser-crap: https://github.com/irisli/stellarterm/blob/master/src/lib/driver/Send.js

**Comment by janclarin** [comment]
Seems weird that the session is being refactored into Send. Technically Balances also uses it and other components may too. Thoughts?

**Comment by janclarin** [comment]
Actually, my deleted comment still holds. Thought I missed something because I just noticed that you linked line 74, logIn(). Seems weird that logIn() is moving into Send. Shouldn't it be its own place. No?

**Comment by irisli** [comment]
ohhh oops i misworded. none of this stuff should be inside Send.

I just had Send.js (and any of the other stuff here: https://github.com/irisli/stellarterm/tree/master/src/lib/driver ) as the format to follow.

**Comment by janclarin** [comment]
Oh I see. That makes a lot more sense!

**Comment by irisli** [comment]
Done
