### ISSUE TITLE
Can't send asset to the issuer of the asset

### ISSUE THREAD

**Issue by jinhwanlazy** [irisli/stellarterm#149]
I'm building an anchor, https://bosanchor.io/

Users supposed to send their asset directly to the issuer's address so that the asset to be destroyed along with withdrawal. It had been working fine, but It has been blocked since few days ago with following message `Destination does not accept this asset.`

Is it intended behavior, so I should change the design of my anchor?

**Comment by irisli** [comment]
This is not a common usecase, so unfortunately it's not well supported. But if this becomes a common use case for you, I can debug and fix

**Comment by jinhwanlazy** [comment]
i'd appreciate if you do that

**Comment by irisli** [comment]
Alternatively, what you can do is have a distributor account. So the issuer account is only a cold-account. That way, it'll be harder to hack

**Comment by jinhwanlazy** [comment]
Yah, That's what official document told me to do. But I thought my expected customers will not be happy seeing pregenerated assets. I wanted them to see themselves the exact amounts are issued and destroyed every time deposit and withdraw are made.

**Comment by irisli** [comment]
If you send to a issuer, it'll be a black hole. And it's a bit more risky like that. But yeah, thats one benefit

**Comment by irisli** [comment]
Someone else fixed it :)
