### ISSUE TITLE
Hacked? My 300 XLM has been disappeared.

### ISSUE THREAD

**Issue by takhub** [irisli/stellarterm#150]
I received 300 XLM from my friend on Jan 11 and I actually confirmed that I received it on StellarTerm.
But it has been disappeared when I checked my balance yesterday.
Could you explain what is going on and how to get it back to me?

Public Key: GBZZZCYYMG4KW64EIUIYHMHWYRIQEFRDTJJNVLLWFRUNL7SMW7Z6EJDY

**Comment by irisli** [comment]
This is probably from the Stellar invite system. They said that if you don't move your lumens, they will take it back. So this is porbably what happened

**Comment by takhub** [comment]
Hi Iris, thank you for prompt answer. Yes, you were right.
And Stellar just gave it back to me.
I'm so sorry for my misunderstanding!

**Comment by irisli** [comment]
Okay, nice :)
