### ISSUE TITLE
An unknown error occured

### ISSUE THREAD

**Issue by vitaaum** [irisli/stellarterm#152]
When I click on any of the tabs: historic, send, balance, inflation and accept assets the following error occurs:

An unexpected error happened. If you want to help this error get fixed, please report it to the GitHub issue tracker. DO NOT SHARE YOUR PRIVATE KEY WITH ANYONE (begins with an S).

Your funds are safe and not affected by this error. This error is just a display error in StellarTerm.

TypeError: Cannot read property 'split' of undefined
    at n.niceDate (https://stellarterm.com/:23:945039)
    at https://stellarterm.com/:23:696506
    at Array.map (<anonymous>)
    at t.value (https://stellarterm.com/:23:696367)
    at a (https://stellarterm.com/:23:400627)
    at beginWork (https://stellarterm.com/:23:402335)
    at r (https://stellarterm.com/:23:414456)
    at s (https://stellarterm.com/:23:414777)
    at i (https://stellarterm.com/:23:415015)
    at E (https://stellarterm.com/:23:418555)
    at w (https://stellarterm.com/:23:418292)
    at h (https://stellarterm.com/:23:417421)
    at p (https://stellarterm.com/:23:416811)
    at Object.enqueueSetState (https://stellarterm.com/:23:391412)
    at t.d.setState (https://stellarterm.com/:23:532272)
    at https://stellarterm.com/:23:596044

    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in div
    in t

Public key: GD6ZED54G3J2EROBZMU63U6E4FSOHWHK325RIZAPLTDWTHIKWTLWRLFS

**Comment by franciscodsj** [comment]
How to fix this ??

Ocorreu um erro desconhecido
Ocorreu um erro inesperado. Se você quiser ajudar a corrigir este erro, informe-o para o rastreador de problemas do GitHub . SE NÃO COMPARTILHE sua chave privada com ninguém (começa com um S).

Seus fundos são seguros e não são afetados por esse erro. Este erro é apenas um erro de exibição no StellarTerm.

Erro: Falha ao executar 'removeChild' no 'Node': O nó a ser removido não é filho desse nó.
    em removeChild (https://stellarterm.com/:23:460360)
    em i (https://stellarterm.com/:23:407393)
    em commitDeletion (https://stellarterm.com/:23:408938)
    em t (https://stellarterm.com/:23:412915)
    em E (https://stellarterm.com/:23:418591)
    em w (https://stellarterm.com/:23:418292)
    em h (https://stellarterm.com/:23:417421)
    em p (https://stellarterm.com/:23:416811)
    em Object.enqueueSetState (https://stellarterm.com/:23:391412)
    em tdsetState (https://stellarterm.com/:23:532272)
    em https://stellarterm.com/:23:596044

    em div
    em div
    em div
    em Desconhecido
    em t
    em div
    em t
    em div
    em t

**Comment by irisli** [comment]
Can you give me the error output on the new version of StellarTerm? And also steps on how to recreate this. Thanks
