### ISSUE TITLE
hi  i have  transfer xlm to biance

### ISSUE THREAD

**Issue by cy2408** [irisli/stellarterm#153]
this ibformation below, i want to find the transfer in stellarterm.com,  biannce wnat to show this, i can find my xlm.
2. xlm
3. 1300
4 txid  b044c33b56f6dbb4128ff91454c19e24c327a8def7e000d37a0c36ebc7786615

**Comment by irisli** [comment]
You can see this in stellar.expert: https://stellar.expert/explorer/tx/b044c33b56f6dbb4128ff91454c19e24c327a8def7e000d37a0c36ebc7786615
