### ISSUE TITLE
Stellarterm - Failed to Create offer (Exchanging XLM for another asset)

### ISSUE THREAD

**Issue by stellaruserSM** [irisli/stellarterm#154]
![stellarterm error - buy](https://user-images.githubusercontent.com/35917672/35503525-ca436d06-04f9-11e8-8143-32be956d53d0.jpg)

Hello,
I am having an issue, where i get an error whenever i try to create an offer to buy another asset using my XLM, Please advise how to resolve, I am not trading the full qty of XLM, i am keeping approx. 10 XLM balance. 

Please advice,

**Comment by irisli** [comment]
I'm guessing you tried to manually create the trustline from somewhere? It says your trustline is too full, so you need to make a new trust line with a bigger limit

**Comment by irisli** [comment]
Here is a guide: https://medium.com/@dgobaud/mobius-stellarterm-guide-7b6a051324ad

**Comment by stellaruserSM** [comment]
Thank you very much, this solves my issue :)
