### ISSUE TITLE
allow non-uppercase custom asset name

### ISSUE THREAD

**Issue by wkta** [irisli/stellarterm#157]
When trying to type the name of an asset in the
"Custom exchange pair",
the asset name is automatically capitalized.

This constitutes a problem in case of assets named, for example:  GTTpresale1, or CM3x2 or any valid asset name which includes lowercase characters

**Comment by irisli** [comment]
Good point

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/blob/master/src/components/AssetPickerNarrow.jsx#L19

Just have to remove a few characters

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/pull/162

Thanks
