### ISSUE TITLE
I didn't get my cancelled order balance back into my account.

### ISSUE THREAD

**Issue by lbn349** [irisli/stellarterm#158]
This has happened twice now in the past hour. i am now afraid to cancel two pending orders on stellarterm, because the cancelled balance is not going back into my account. Who should i contact about this? I will post my public key upon request, this is a horrible bug

**Comment by lbn349** [comment]
view screenshot below, first image is with the pending order. second is after cancelling order. third is after refreshing stellar term, and balance still at 0. i will send my public key in a private message preferably to keep balance private 
![xlm](https://user-images.githubusercontent.com/35014105/35739235-f9ee890c-07fe-11e8-84fd-cb5e4a905a96.png)

**Comment by irisli** [comment]
The Stellar decentralized exchange is different from a regular exchange. When you make offers, it doesn't remove what you have. Since there was nothing spent, there was also nothing to refund.
