### ISSUE TITLE
StellarTerm does not allow you to send assets to their issuer

### ISSUE THREAD

**Issue by jackkleeman** [irisli/stellarterm#160]
Sending assets back to issuer is critical for the operation of anchors.
StellarTerm presumably checks the recipient balance to see if they trust an asset
However issuers cannot trust themself. So StellarTerm should allow you to send an asset to its issuer.

**Comment by jackkleeman** [comment]
Despite adding to available assets here:
https://github.com/irisli/stellarterm/blob/b750076dbe0d88f3f0e11b23c7eb332c098369f1/src/lib/driver/Send.js#L99
This is overwritten here:
https://github.com/irisli/stellarterm/blob/b750076dbe0d88f3f0e11b23c7eb332c098369f1/src/lib/driver/Send.js#L143
and here:
https://github.com/irisli/stellarterm/blob/b750076dbe0d88f3f0e11b23c7eb332c098369f1/src/lib/driver/Send.js#L154

**Comment by jackkleeman** [comment]
See PR here https://github.com/irisli/stellarterm/pull/161

**Comment by janclarin** [comment]
This can be marked as resolved

**Comment by irisli** [comment]
Thanks @jackkleeman!
