### ISSUE TITLE
如何解决

### ISSUE THREAD

**Issue by yangyun1976** [irisli/stellarterm#164]
代码  问题67 拉取请求1 脉冲    
跳到底部 打开
如何解决这个问题？ ＃155
@franciscodsj
franciscodsj
7天前 开通了这个问题 
发生未知错误发生
意外错误。如果您想帮助解决此错误，请将其报告给GitHub问题跟踪器。不要与任何人分享您的私钥（以S开头）。

您的资金是安全的，不会受到此错误的影响。这个错误只是StellarTerm中的一个显示错误。

错误：无法在“节点”上执行“removeChild”：要删除的节点不是此节点的子节点。
在删除（https://stellarterm.com/:23:460360）
在我（https://stellarterm.com/:23:407393）
在commitDeletion（https://stellarterm.com/:23:408938）
在t （https://stellarterm.com/:23:412915）
在E（https://stellarterm.com/:23:418591）
在W（https://stellarterm.com/:23:418292）
在H（HTTPS ：//stellarterm.com/：23：417421）
at p（https://stellarterm.com/:23:416811）
在Object.enqueueSetState（https://stellarterm.com/:23:391412）
在tdsetState（https://stellarterm.com/:23:532272）
在https://stellarterm.com/:23:596044

in div
in div
in div
in Unknown
in t
in div
in t
in div
in t
@irisli
irisli 
评论道 5天前
你使用的是什么浏览器？

@franciscodsj
franciscodsj 
评论 3天前
谷歌浏览器！！

对问题进行评论
 
Leave a comment
评论
此线程的通知
您没有收到来自此主题的通知。

  订阅
 桌面版本

**Comment by irisli** [comment]
Can I have a screenshot/picture?

**Comment by yangyun1976** [comment]
怎么截图

**Comment by irisli** [comment]
What is your Account ID?

What do you do to make the error show?
