### ISSUE TITLE
Ticker 24h price difference

### ISSUE THREAD

**Issue by irisli** [irisli/stellarterm#167]
It'd be nice to show the 24 hour change in percentage in the markets page. Kinda like how Coinmarketcap shows it

**Comment by irisli** [comment]
You are also welcome to add whatever features to the ticker you think is good :)

**Comment by irisli** [comment]
I implemented this today

**Comment by janclarin** [comment]
Sounds good! I was looking into the code just now, but that works too. Been busy with work stuff.
