### ISSUE TITLE
如何解决

### ISSUE THREAD

**Issue by yangyun1976** [irisli/stellarterm#169]
发生未知错误发生
意外错误。如果您想帮助解决此错误，请将其报告给GitHub问题跟踪器。不要与任何人分享您的私钥（以S开头）。

您的资金是安全的，不会受到此错误的影响。这个错误只是StellarTerm中的一个显示错误。

错误：无法在“节点”上执行“removeChild”：要删除的节点不是此节点的子节点。
在删除（https://stellarterm.com/:23:460360）
在我（https://stellarterm.com/:23:407393）
在commitDeletion（https://stellarterm.com/:23:408938）
在t （https://stellarterm.com/:23:412915）
在E（https://stellarterm.com/:23:418591）
在W（https://stellarterm.com/:23:418292）
在H（HTTPS ：//stellarterm.com/：23：417421）
at p（https://stellarterm.com/:23:416811）
在Object.enqueueSetState（https://stellarterm.com/:23:391412）
在tdsetState（https://stellarterm.com/:23:532272）
在https://stellarterm.com/:23:596044

in div
in div
in div
in Unknown
in t
in div
in t
in div
in t丨

**Comment by irisli** [comment]
Can you try on the new StellarTerm and show me what it says.
