### ISSUE TITLE
Add CHRC 

### ISSUE THREAD

**Issue by jonasess** [irisli/stellarterm#183]
[inforamtion.txt](https://github.com/irisli/stellarterm/files/1713768/inforamtion.txt)
hi . i would like to request you to add Charna Token (CHRC) to exchanging and reviewing that we meet all the requirement .
these are the information :
website : http://charnatoken.top
"code": "CHRC",
"issuer": "GBRPTWEZTUKYM6VJXLHXBFI23M2GSY3TCVIQSZKFQLMOJXH7VPDGKBDP"

I attached the icon of CHRC .
an other information please let us know
thank you
![charnatoke top](https://user-images.githubusercontent.com/13025030/36066823-49186efe-0eb1-11e8-9bb7-d0015fe226c6.png)

**Comment by irisli** [comment]
Can you make a pull request with the changes?

**Comment by jonasess** [comment]
okay wait

**Comment by jonasess** [comment]
done

**Comment by jonasess** [comment]
can you help me please?
how to add CHRC ?
