### ISSUE TITLE
add CHRC

### ISSUE THREAD

**Issue by jonasess** [irisli/stellarterm#188]
Hello . i have been trying to add CHRC but i couldn't
so could you please add our CHRCcoin please? Thanks
here are the information :
the logo
https://charnatoken.top/wp-content/uploads/2018/02/CharnaToke.top_.png
stellar toml file
https://charnatoken.top/.well-known/stellar.toml

brand color is #1c4664

other information from toml file

code="CHRC"
issuer="GBRPTWEZTUKYM6VJXLHXBFI23M2GSY3TCVIQSZKFQLMOJXH7VPDGKBDP"
name="Charna Token"
desc="Charna Token will benefit from projects involving AI, and blockchain technology (aitca.net). it also has a mass market opportunity as a utility token"
conditions="Only 450 million tokens will ever be issued. You can get Charna token by buying/or trading for it on the Stellar network or exchanges were stellar is accepted"
image="https://charnatoken.top/wp-content/uploads/2018/02/CharnaToke.top_.png"

![charnatoke top](https://user-images.githubusercontent.com/13025030/36079670-fb0d2490-0f85-11e8-9e7d-dca67c944f90.png)

**Comment by jonasess** [comment]
please can you add it ? or at least tell us what's missing ?

**Comment by jonasess** [comment]
Irisli can you reply please and help?

**Comment by irisli** [comment]
Hi,

I expanded the requirements on here: https://github.com/irisli/stellarterm/tree/master/directory

Can you show me the 7 requirements are met

**Comment by jonasess** [comment]
Hello irisli .
yes we have all the requirements please check it
 1/ you will find the Asset explanation in the website .
2/check the website you will find the dev team info ... etc
3/we enabled the Website SSL . https://charnatoken.top/
4/Stellar.toml hosted on your site . we already done from it https://charnatoken.top/.well-known/stellar.toml
5/we also done from CORS configuration .
6/ the logo of Square is ready .
7/this is our brand color #1c4664

so all the requirements are met .
waiting for your reply .
thanks

**Comment by jonasess** [comment]
At least if there's something missing or doesn't met the requirements let us know . 
Because all the 7 steps (requirements) are setted up

**Comment by jonasess** [comment]
We believe we have all requirements done for listing . if we miss any can you let us know so we can fix it .
thanks

**Comment by irisli** [comment]
done
