### ISSUE TITLE
Error accepting asset XIR

### ISSUE THREAD

**Issue by xirkle** [irisli/stellarterm#194]
Hi Iris,

I login into my account on StellerTerm and I tried to accept XIR; however, it gave me an error message.
"Error accepting asset XIR"

What's causing this error message? How do I/we fix it?

Yes, I can still add it manually.

Thank you!

**Comment by irisli** [comment]
It works for me. Maybe you need more XLM?

**Comment by xirkle** [comment]
I have 57 XLM in my account. Is that not enough?

**Comment by irisli** [comment]
Can you send me your public key

**Comment by irisli** [comment]
You can send me through a private message
