### ISSUE TITLE
UX: Reccomended XLM minimum for an account

### ISSUE THREAD

**Issue by WallBB** [irisli/stellarterm#205]
Hi irisli,
I think there might be an issue for new accounts related to minimum balance. 

You can follow these steps -
1. Suppose you create an account on public network
https://www.stellar.org/laboratory/#account-creator?network=public
2. Once you login using the private key you will see below message -

> To use your Stellar account, you must activate it by sending at least 5 lumens (XLM) to your account. You can buy lumens (XLM) from an exchange and send them to your address.

I believe that the amount might be incorrect based on minimum balance calculation -

The Stellar network requires accounts to maintain a minimum balance. A 1 XLM minimum balance is required with an additional requirement 0.5 XLM for each entry in the account such as a trustline or offer. You can read more about this on the Stellar developer docs
Each entry (asset accepted, offer, signer) increases your minimum balance by 0.5 XLM. Additionally, StellarTerm enforces a 0.1 XLM of extra minimum balance in an attempt to make sure your account can still make transactions without going below the network minimum balance requirements.

Looking forward to your response, I didn't find any doc regarding 5 XLM minimum fees hence created this issue :)

**Comment by irisli** [comment]
5 is an arbitrary number.

But if users create an acount with 1.0 XLM, it's basically useless. They can't do anything.

With 1.5, they can make a trust line, but can't make an offer.

5 enables 2 trust lines and 4 offers, which is good enough

**Comment by WallBB** [comment]
I understand the reason why it is 5 XLM :+1: 
I feel this message should be modified as it is a little unclear message 

> To use your Stellar account, you must activate it by sending at least 5 lumens (XLM) to your account. You can buy lumens (XLM) from an exchange and send them to your address.

**Comment by irisli** [comment]
Yeah, it's unclear, but it helps users

**Comment by WallBB** [comment]
Yes, I will say a better message will be 

> To use your Stellar Term account, you must activate it by sending at least 5 lumens (XLM) to your account. You can buy (XLM) from an exchange and send them to your address

Just my suggestion as that will be more clear ^

**Comment by WallBB** [comment]
Closing this issue now, I hope irisli you think something about this :)
Even a modal popup with more information will be awesome.

**Comment by irisli** [comment]
A much better onboarding flow is actually being designed, so this old messaging will be completely revamped.
