### ISSUE TITLE
Critical Security Flaw in Stellarterm

### ISSUE THREAD

**Issue by riomyers** [irisli/stellarterm#215]
I have found a serious flaw in https://stellarterm.com/ in which it's very easy to download an exact copy of the website which fully functions like the original, a malicious person could then host this website on a similar looking domain name like stellartern.com or stelarterm.com or stellaterm.com for example which not everyone would notice the spelling error unless they're paying close attention. The website copy will also function on the other domain normally, this includes the ability to create accounts, send and receive lumens (tested with my own ledger and my own accounts), use the exchange, etc, so it literally functions like the entire website. They could then easily add an ID to the secret key input using `id:nameofID` and then target that ID using a javascript function to extract the data that is inputted into the form field on submit and save the secret key store to a .txt file. This would then allow the malicious person to have full access to anyone's funds that incorrectly assumed they were using the official website since they now have their private key stored in the .txt file. I have not added the malicious code to the test I created but I have kept it here: https://riomyers.com/stellar/ so you can see how the website functions exactly like the original stellarterm.com site despite being on a different domain name, since I'm also using https there are no security flags that appear indicating that the site may be unsafe which would further allow someone to take advantage of this flaw since the website seems completely normal, the only difference is the domain. They could probably get to the point of even creating functions where they can have XLM sent to their own addresses if they spend enough time manipulating the code, this seems unnecessary since they already have the secret key which now allows full control of the person's funds but there are many flaws this creates that could be taken advantage of using a similar method as described above.

**Comment by irisli** [comment]
You're just describing a phishing attack. This isn't a serious flaw in stellarterm and could be applied to every other site in the world (someone could make a site that looks like Facebook).

Even if I add code in stellarterm to check for the url, phishers can trivially edit the code out.

**Comment by riomyers** [comment]
Then I guess it's even more of a flaw that anyone would require you to enter the secret key to login to your account in the first place. At the very least it should be password protected.

**Comment by irisli** [comment]
Password protection is just another form of entering a secret key.

It is true that web wallets have a wider surface area of attacks, so thats why there is the desktop client.

**Comment by riomyers** [comment]
@irisli understandable, it's up to the user to handle their own security anyways. I appreciate your replies.
