### ISSUE TITLE
Failed the transaction of send payment with the error code, tx_bad_seq

### ISSUE THREAD

**Issue by richgrove** [irisli/stellarterm#225]
I downloaded and ran the latest stellarterm on the local to connect to the testnet:
     STELLARTERM_CUSTOM_HORIZON_URL=https://horizon-testnet.stellar.org
     npm start
then, I logged in test stellar account with the secret key.   It shows the custom asset created and assigned to me.  Then, I tried to send the payment to another account (who also trusted the custom asset).   After the transaction is created, and submit failed at:

```
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAACAK26VIFRZf6PYSrT2dW9sZL4iTcndXJ+G5j46fvSofAAAAZAB3JiQAAAASAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAbGqe0KgZR4INEuVtWOUNiiRpzaPKNgu7wHOweMIlIokAAAACdGVzdDIAAAAAAAAAAAAAABg0DWfk4Vtn5ZuQ0NO3a5RvgLrrUqy0P96gk6G93k59AAAAAAcnDgAAAAAAAAAAAZ+9Kh8AAABAQcQxPiRG6GYIbCmm9TxjjQoSEzbX1Mf86ykPD6CeDonDxUfjBDGXl7fJNp+9W7tW9Bx9UtywRjldHBCz6NjcBA==",
    "result_codes": {
      "transaction": "tx_bad_seq"
    },
    "result_xdr": "AAAAAAAAAAD////7AAAAAA=="
  }
}
```
I don't know why this happened, and everything looks right for me.   Please help it.  Thanks.

**Comment by richgrove** [comment]
Here is the request header:

```
POST /transactions HTTP/1.1
Host: horizon-testnet.stellar.org
Connection: keep-alive
Content-Length: 341
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Comment by richgrove** [comment]
BTW, the custom asset was issued by:
   issuer:  GBKUPN72DL7576JBUU565QCKSJISTZ4ORL2CMHLCLGVAKACKO5S7MNZR
   assetcode: test3
https://horizon-testnet.stellar.org/assets/?issuer=GBKUPN72DL7576JBUU565QCKSJISTZ4ORL2CMHLCLGVAKACKO5S7MNZR&assetcode=test3

**Comment by irisli** [comment]
The environment variables might not be set correctly since there are two things: https://github.com/irisli/stellarterm#custom-horizon-builds

Also, if you want to use testnet, you don't need to compile. Just go to `#testnet` like so: https://stellarterm.com/#testnet

As for the sequence error problem, it usually goes away after refreshing. Can you try again on `#testnet` to see if the problem still happens?

**Comment by richgrove** [comment]
Yes, using the https://stellarterm.com/#testnet, the transaction was created successfully.
https://horizon-testnet.stellar.org/transactions/255b28aba8904584566a0e91bc6af11b8afa3852522733d1d46455f68a628a99

Also, after configured both testing environment variables, it works perfectly.  Thanks.

**Comment by irisli** [comment]
@Verax101 If you are using the default StellarTerm, then this is not the same issue as in this issue #225.

To fix, you'll just have to refresh the client.

**Comment by Verax101** [comment]
Thanks for response, but refreshing the does not help. The problem seems to have started after removing multisig and mistakingly leaving low threshold at 2 when medium and and high at 0. And now, I can't change the low threshold  0 as transactions fail. Is there a way reset low threshold 0. Please help.

**Comment by irisli** [comment]
StellarTerm doesn't do multisig and is unable to fix this issue. Maybe you can find some stellar support
