### ISSUE TITLE
Why don't the buy and sell prices default to last best market prices? or add a button to do so

### ISSUE THREAD

**Issue by sacarlson** [irisli/stellarterm#34]
Why don't the buy and sell prices default to last best market prices?  or maybe we need to add a button that fills in present lowest sell offer in Buy Price per box and fills Sell Price per box with highest Buy offer

**Comment by irisli** [comment]
![image](https://user-images.githubusercontent.com/5728307/28649643-2a6ea284-722b-11e7-91f7-3ecf0e058778.png)
They supposedly do
