### ISSUE TITLE
Add federation to Send

### ISSUE THREAD

**Issue by breznikov7** [irisli/stellarterm#47]
![screen shot 2017-08-10 at 10 42 11 am](https://user-images.githubusercontent.com/22531215/29183743-a981cc66-7db8-11e7-884b-79848b1ae0f8.png)

When sending lumens federated address is marked as invalid account ID.

**Comment by irisli** [comment]
Ab, yes thats because I haven't implemented federation in send. There are so many edgecases in sending

**Comment by irisli** [comment]
Added and live now
