### ISSUE TITLE
Support lowercase trust line

### ISSUE THREAD

**Issue by breznikov7** [irisli/stellarterm#48]
Add support for lower case asset codes when manually adding a trust line
(it's possible to issue tokens with lowercase letters when using alphanumeric 12)

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/commit/86a364d68b5607c2c9db5d2ced8821b790d6c1d7

Done thanks

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/commit/86a364d68b5607c2c9db5d2ced8821b790d6c1d7

Done thanks
