### ISSUE TITLE
Please add icon to BorisCoin

### ISSUE THREAD

**Issue by breznikov7** [irisli/stellarterm#49]
This is super low priority (obviously) but if you have a second please add this as the icon for BorisCoin (icon attached)

Issuing acct: GBAAP5XTMQBGP5HEE7KG2HDIXKWXE7U4XXDT5ZX2BRWU6C4R6B2LE556

![boriscoin icon](https://user-images.githubusercontent.com/22531215/29231044-7003473e-7e9a-11e7-8603-25e2e60cc17f.jpg)

**Comment by irisli** [comment]
Details have been resolved.
