### ISSUE TITLE
show balances on the send page

### ISSUE THREAD

**Issue by jedmccaleb** [irisli/stellarterm#58]
Really annoying to not know what your balance is when you are trying to send. Probably put this in Step 2 where it allows you to pick the asset you are sending.

**Comment by irisli** [comment]
Yeah important!

**Comment by robertDurst** [comment]
Hey @irisli I see that there is a contribution label here and I was wondering if this is still an issue? I agree that moving asset balance to step 2 would be very helpful so that you can choose asset based on balance -- maybe even show minimum balance here as well?

**Comment by irisli** [comment]
Yes, that would also be useful. You can contribu

**Comment by sdtsui** [comment]
@irisli shall we close this? Looks like it exists in Step 3:
![](https://puu.sh/zo6Rk/0cdcea9fd8.png)

**Comment by irisli** [comment]
Yeah, lets close, then do a overhaul of send
