### ISSUE TITLE
Add new token to directory listing

### ISSUE THREAD

**Issue by skraba** [irisli/stellarterm#60]
Could you please add Liquido token to your directory listing? 

Logo file is attached and meets specifications (100x100px, png  etc).
I'm also attaching relevant data for directory listing, hoping that this is everything.
Is it possible to name it just "liquido" instead of "liquido.i-server.org" ? if not, no problem ;)

![liquido i-server org](https://user-images.githubusercontent.com/27896979/30037447-1b619d1e-91bb-11e7-8274-3395598a90c1.png)

[directory.js.diff.txt](https://github.com/irisli/stellarterm/files/1275429/directory.js.diff.txt)

Thank you!

**Comment by irisli** [comment]
Done
