### ISSUE TITLE
add NGN Flutterwave

### ISSUE THREAD

**Issue by tempofr** [irisli/stellarterm#66]
Please add flutterwave

curl https://www.flutterwave.com/.well-known/stellar.toml
[[CURRENCIES]]

code="NGN"
issuer="GCDDLQIGVK6WO4KNZBCL3BXFDX5AONZVJCFJTOOXGU2DXWY3TPCP3PYG"
display_decimals=2

**Comment by irisli** [comment]
Will add once the StellarTerm directory upgrade code is finished: https://github.com/irisli/stellarterm/tree/directory-upgrade

**Comment by tempofr** [comment]
updated.... including image thanks
[[CURRENCIES]]

code="NGN"
issuer="GCC4YLCR7DDWFCIPTROQM7EB2QMFD35XRWEQVIQYJQHVW6VE5MJZXIGW"
display_decimals=2
image="https://www.flutterwavedev.com/images/logo.dark.png"

**Comment by irisli** [comment]
Done

**Comment by PhelimonSarpaning** [comment]
Is flutterwave still an anchor on stellar?

**Comment by tempofr** [comment]
Not currently

Anthony BARKER
