### ISSUE TITLE
Sync sequence number when streaming account details. Fixes: tx_bad_seq when adding a trustline

### ISSUE THREAD

**Issue by chatch** [irisli/stellarterm#74]
i just got a tx_bad_seq when trying to add a new trustline. I think it's because i'd submitted a transaction in different wallet in between logging into stellarterm and trying to add the trustline ..

when i logged out and logged back in to stellarterm then the trustline add worked fine.

so presumably the seq number is being kept in memory?

**Comment by irisli** [comment]
Ah, yeah the seq number is fetched then locally stored. Perhaps I should sync it when I stream account

**Comment by irisli** [comment]
Thanks!

**Comment by jedmccaleb** [comment]
I think it is fine to cache it locally. but maybe try to refetch it if any tx gets a `tx_bad_seq` error

**Comment by irisli** [comment]
Oh good point! If a tx gets a tx_bad_seq, then I'll immediately force the Account to update again.

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/commit/df09c3711d4f0333bf92625f58c26bdfd5e6f310

Boom! 1 minute fix!

I think this should already cover all the cases since it updates sequence number every ledger close. Any other way would be overkill.
