### ISSUE TITLE
Clean up assets listed 

### ISSUE THREAD

**Issue by jedmccaleb** [irisli/stellarterm#78]
I'd remove:
- NGN readycash
- Demo

I'd add:
- apay.io anchor and assets
- XEL issued by naobtc

**Comment by tomerweller** [comment]
@jedmccaleb, looks like these are coming from the ticker: https://api.stellarterm.com/v1/ticker.json

**Comment by irisli** [comment]
Yup and the ticker info comes from the directory

**Comment by tomerweller** [comment]
Thanks. I was confused by the existence of the other ticker project.
