### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by irisli** [irisli/stellarterm#80]
I really like the way the Rippletrade client did it. They let you filter by operation types.

Then, once I have the transaction history set up, StellarTerm can also act as a account explorer! Feature creep like blockchain.info!

**Comment by robertDurst** [comment]
Hey, I've been checking out Stellarterm and agree transaction history would be a cool feature. I am familiar with blockchain.info, but not so much with Rippletrade. Since Rippletrade is down, I was wondering if you knew of similar example. Thanks!

**Comment by irisli** [comment]
The way I propose is that the client would show all the "effects" of things that happened to your account such as receiving a transaction, changing signers and settings, and offers. Then, it will be easily possible to filter these effects with checkboxes.

**Comment by robertDurst** [comment]
I see, so more of an "account history" than just a simple transaction history of all payments in and out.

**Comment by robertDurst** [comment]
Hey @irisli just want to let you know I've been working on this and will probably submit a PR tonight! Here is what I came up with:
![effectstabledemo](https://user-images.githubusercontent.com/16689974/33234242-13edec2e-d1d8-11e7-8577-4f4ea6ee66cd.gif)
