### ISSUE TITLE
transpile directory.js before npm publish

### ISSUE THREAD

**Issue by chatch** [irisli/stellarterm#93]
I'm pulling the stellarterm-directory package into steexp now which is really nice. i've changed the anchors list view to build off of it including the logos etc.

however when i webpack up everything it fails due to ES5(6?) code inside the directory package main script directory.js. this code should be transpiled before being published into npm. or alternatively the directory.json could be made the package main.

**Comment by irisli** [comment]
Oh, the directory.json is supposed to be checked in. And also, the directoryBuilder.js works in Node.js v8 natively.

Try updating your Node.js to the latest version 8. I'm not going to support v6 since v8 has long term support (in a few days).

**Comment by irisli** [comment]
Maybe try again using node version manager. And if it still doesn't work, i'll take a look again. But I'm pretty sure you should just use a newer version of nodejs

**Comment by chatch** [comment]
the problem is not the node version but my toolchain, specifically create-react-app invoking minify.  it assumes the javascript in all the npm dependencies it's minifying has been precompiled to es5. which is not the case for the directory. 

I found they write about this in create-react-app docs : https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

but actually I read what you wrote under "manually using the JSON" and really all I need is that directory.json. so, I reckon I'll just pull that it in manually and that'll do it.

btw. this is the build error from react : https://travis-ci.org/chatch/stellarexplorer/jobs/290854404#L490

**Comment by irisli** [comment]
Oh i see the issue now. I used ES6 class. Thanks!

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/commit/bad47bfe968bbdc4d11b7259050e58c83ccd295c

I fixed it here hopefully. Try again and let me know how it goes please
