### ISSUE TITLE
Supported payment types to stellarterm-directory package

### ISSUE THREAD

**Issue by s-a-y** [irisli/stellarterm#97]
Found this:
https://www.reddit.com/r/Stellar/comments/79ptfi/warning_do_not_use_bittrex_for_stellar_they/

Would be useful to have list of supported payment methods for destinations, who accepts payment / path_payment / merge
and protect users from making mistakes

**Comment by irisli** [comment]
Hm perhaps all destinations can default to be unmergeable. And then only add merge when it's accepted. I don't think I will be adding merging to StellarTerm soon after seeing this issue though.

**Comment by irisli** [comment]
Thanks!

**Comment by s-a-y** [comment]
Oh, that was fast!
However I think there is one more thing to it: path payments.
Exchanges are not listening to path payments, so you can set default to false as well and I will later update PapayaBot and PapayaSwap to enable it.

**Comment by irisli** [comment]
Done!
