### ISSUE TITLE
Issue when sending XLM

### ISSUE THREAD

**Issue by cmunkres** [irisli/stellarterm#98]
When I go to transfer my XLM to my wallet, I get the following error message showing below. The transaction fee was taken though.

Error
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "instance": "horizon-live-001/jyEwd0dy8s-35802547",
  "extras": {
    "envelope_xdr": "AAAAADAenO1A0p0GtIvaR8rm9uO25+c4if7Mh3amQUw1ajtbAAAAZADaE1wAAAADAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAoNYbCUl5r6IPwUFsZYjCAnHzK2x5u+zOqB7XxTyelVQAAAAAO5e8wAAAAAAAAAABNWo7WwAAAEDpYhvpVIOJSYC9qtC803h3avb1GgE+fmq86F7bI9oSoJKiWfRui0qIxX0g5Mj8X0ulZFwuOWQeqPLxr7nJd/gH",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_underfunded"
      ]
    },
    "result_xdr": "AAAAAAAAAGT/////AAAAAQAAAAAAAAAA/////gAAAAA="
  }
}

**Comment by irisli** [comment]
It means you don't have enough lumens

**Comment by irisli** [comment]
I added a more detailed error message system.
